### PR TITLE
HELPPPPPP i don't know where to go

### PR DESCRIPTION
**Pull request by hmg346**
help me im sure this isn't the right place to ask but the only one I could fine. I am totally new to this tried to creat the Alexa/roku install but its now working an I have no idea why as im totally new to this. I seen at least 12 hours trying to do it can someone help me.   please!

### CODE REVIEW

**Comment by cmon69** [comment]
Are you using a Raspberry Pi?

**Comment by hmg346** [comment]
I'm trying to do the programming part on my imac.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Christapher Hasher <notifications@github.com> Date: 4/27/18  17:10  (GMT-07:00) To: julianh2o/RokuAlexaLambdaSkill <RokuAlexaLambdaSkill@noreply.github.com> Cc: hmg346 <hmg346@gmail.com>, Author <author@noreply.github.com> Subject: Re: [julianh2o/RokuAlexaLambdaSkill] HELPPPPPP i don't know where to
  go (#32) 
Are you using a Raspberry Pi?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/julianh2o/RokuAlexaLambdaSkill","title":"julianh2o/RokuAlexaLambdaSkill","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/julianh2o/RokuAlexaLambdaSkill"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cmon69 in #32: Are you using a Raspberry Pi?"}],"action":{"name":"View Pull Request","url":"https://github.com/julianh2o/RokuAlexaLambdaSkill/pull/32#issuecomment-385123224"}}}

**Comment by hmg346** [comment]
iMac. The programming  on the amazon developer site. However the interface is different than the users guide that was put out. I ended up having to hand type all of the intents and things.  When I did the final portion  there were about ten  errors given why it didn't run.  AMD I don't know what any of the errors mean.

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Christapher Hasher <notifications@github.com> Date: 4/27/18  17:10  (GMT-07:00) To: julianh2o/RokuAlexaLambdaSkill <RokuAlexaLambdaSkill@noreply.github.com> Cc: hmg346 <hmg346@gmail.com>, Author <author@noreply.github.com> Subject: Re: [julianh2o/RokuAlexaLambdaSkill] HELPPPPPP i don't know where to
  go (#32) 
Are you using a Raspberry Pi?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/julianh2o/RokuAlexaLambdaSkill","title":"julianh2o/RokuAlexaLambdaSkill","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/julianh2o/RokuAlexaLambdaSkill"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cmon69 in #32: Are you using a Raspberry Pi?"}],"action":{"name":"View Pull Request","url":"https://github.com/julianh2o/RokuAlexaLambdaSkill/pull/32#issuecomment-385123224"}}}

**Comment by hmg346** [comment]
No I am doing the programming on my imac here are the errors I am getting when I type node server.js

 

SyntaxError: Invalid or unexpected token

    at new Script (vm.js:74:7)

    at createScript (vm.js:246:10)

    at Object.runInThisContext (vm.js:298:10)

    at Module._compile (internal/modules/cjs/loader.js:646:28)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)

    at Module.load (internal/modules/cjs/loader.js:589:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)

    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)

**Comment by cmon69** [comment]
Sorry I won't be of any help.

**Pull request closed without merging**
